export const REGISTER_SAGA = "REGISTER_SAGA";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_INIT = "REGISTER_INIT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SAGA = "LOGIN_SAGA";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SAGA = "LOGOUT_SAGA";
export const LOGOUT = "LOGOUT";


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";