export const LOGIN_SAGA = "LOGIN_SAGA";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_ORGANIZATIONS_SAGA = "GET_ORGANIZATIONS_SAGA";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAIL = "GET_ORGANIZATIONS_FAIL";

export const GET_STAFF_SAGA = "GET_STAFF_SAGA";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_FAIL = "GET_STAFF_FAIL";

export const CAMERA_ON = "CAMERA_ON";
export const CAMERA_OFF = "CAMERA_OFF";

export const SET_CHOSEN_ORGANIZATION = "SET_CHOSEN_ORGANIZATION";

export const ADD_USER_SAGA = "ADD_USER_SAGA";

export const SEND_SMS_SAGA = "SEND_SMS_SAGA";
