export const REGISTER_SAGA = "REGISTER_SAGA";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_INIT = "REGISTER_INIT";

export const LOGIN_SAGA = "LOGIN_SAGA";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SAGA = "LOGOUT_SAGA";
export const LOGOUT = "LOGOUT";

export const SEND_DATA_ACTIVE = "SEND_DATA_ACTIVE";
export const SEND_DATA_DISABLE = "SEND_DATA_DISABLE";
export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA";

export const GET_ORGANIZATIONS_SAGA = "GET_ORGANIZATIONS_SAGA";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAIL = "GET_ORGANIZATIONS_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SHOW_BLUR = "SHOW_BLUR";
export const HIDE_BLUR = "HIDE_BLUR";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const REGISTRATION_SCREEN_SHOW = "REGISTRATION_SCREEN_SHOW";
export const LOGIN_SCREEN_SHOW = "LOGIN_SCREEN_SHOW";

export const PIN_AUTHENTICATIED_FALSE = "PIN_AUTHENTICATIED_FALSE";
export const SET_PIN_AUTHENTICATION_SAGA = "SET_PIN_AUTHENTICATION_SAGA";
export const SET_PIN_AUTHENTICATION = "SET_PIN_AUTHENTICATION";
export const REMOVE_PIN_AUTHENTICATION = "REMOVE_PIN_AUTHENTICATION";
export const PIN_AUTHENTICATION_SUCCESS = "PIN_AUTHENTICATION_SUCCESS";


export const GET_LOCAL_DATA_SAGA = "GET_LOCAL_DATA_SAGA";
export const UPDATE_PASSWORD_SAGA = "UPDATE_PASSWORD_SAGA";
export const CHANGE_BIRTHDATE_ACCESS_SAGA = "CHANGE_BIRTHDATE_ACCESS_SAGA";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";
export const SET_CONFIRM_CURRENT_PASSWORD_SAGA = "SET_CONFIRM_CURRENT_PASSWORD_SAGA";
export const CURRENT_PASSWORD_CONFIRMED = "CURRENT_PASSWORD_CONFIRMED";
export const CURRENT_PASSWORD_SET_FALSE = "CURRENT_PASSWORD_SET_FALSE";
